# Generated by Django 6.0.2 on 2026-02-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_resumes', 'Can view all resumes'), ('edit_all_resumes', 'Can edit all resumes')]},
        ),
    ]
