# Generated by Django 6.0.2 on 2026-02-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': [('view_all_resumes', 'Can view all resumes')]},
        ),
    ]
