# Generated by Django 6.0.2 on 2026-02-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
    ]
